FROM python:3.11-slim

WORKDIR /app

COPY frontend/requirements.txt ./requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

# Main Streamlit application
COPY frontend/app.py .

# Streamlit theme and configuration
COPY .streamlit .streamlit

# Application assets

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.address=0.0.0.0", "--server.port=8501"]